// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2619.TubeBot2017;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANJaguar;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.RobotDrive;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANJaguar driveTrainLeftFrontMotor;
    public static CANJaguar driveTrainRightFrontMotor;
    public static CANJaguar driveTrainLeftBackMotor;
    public static CANJaguar driveTrainRightBackMotor;
    public static RobotDrive driveTrainMecanumDrive;
    public static Compressor subCompressorCompressor;
    public static DoubleSolenoid shoulderTopShoulderSolenoid;
    public static DoubleSolenoid shoulderBottomShoulderSolenoid;
    public static CANJaguar elbowElbowMotor;
    public static DoubleSolenoid clawClawSolenoid;
    public static DoubleSolenoid miniBotMinibotSolenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLeftFrontMotor = new CANJaguar(1);
        LiveWindow.addActuator("DriveTrain", "LeftFrontMotor", driveTrainLeftFrontMotor);
        
        driveTrainRightFrontMotor = new CANJaguar(2);
        LiveWindow.addActuator("DriveTrain", "RightFrontMotor", driveTrainRightFrontMotor);
        
        driveTrainLeftBackMotor = new CANJaguar(3);
        LiveWindow.addActuator("DriveTrain", "LeftBackMotor", driveTrainLeftBackMotor);
        
        driveTrainRightBackMotor = new CANJaguar(4);
        LiveWindow.addActuator("DriveTrain", "RightBackMotor", driveTrainRightBackMotor);
        
        driveTrainMecanumDrive = new RobotDrive(driveTrainLeftFrontMotor, driveTrainLeftBackMotor,
              driveTrainRightFrontMotor, driveTrainRightBackMotor);
        
        driveTrainMecanumDrive.setSafetyEnabled(true);
        driveTrainMecanumDrive.setExpiration(0.1);
        driveTrainMecanumDrive.setSensitivity(0.5);
        driveTrainMecanumDrive.setMaxOutput(1.0);

        driveTrainMecanumDrive.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        driveTrainMecanumDrive.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        subCompressorCompressor = new Compressor(0);
        
        
        shoulderTopShoulderSolenoid = new DoubleSolenoid(0, 0, 1);
        LiveWindow.addActuator("Shoulder", "TopShoulderSolenoid", shoulderTopShoulderSolenoid);
        
        shoulderBottomShoulderSolenoid = new DoubleSolenoid(0, 2, 3);
        LiveWindow.addActuator("Shoulder", "BottomShoulderSolenoid", shoulderBottomShoulderSolenoid);
        
        elbowElbowMotor = new CANJaguar(5);
        LiveWindow.addActuator("Elbow", "ElbowMotor", elbowElbowMotor);
        
        clawClawSolenoid = new DoubleSolenoid(0, 4, 5);
        LiveWindow.addActuator("Claw", "ClawSolenoid", clawClawSolenoid);
        
        miniBotMinibotSolenoid = new DoubleSolenoid(0, 6, 7);
        LiveWindow.addActuator("MiniBot", "MinibotSolenoid", miniBotMinibotSolenoid);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
